rootProject.name = 'hextant'

include 'hextant-core'
include 'hextant-test'
include 'hextant-codegen'
include 'hextant-plugins'
include 'hextant-plugins:hextant-common'
include 'hextant-plugins:server'
include 'hextant-launcher'
include 'hextant-plugin-plugin'
include 'hextant-main'
include 'hextant-cli'
include 'hextant-expr'

if (file("../kollektion").exists()) {
    includeBuild("../kollektion")
}
if (file("../reaktive").exists()) {
    includeBuild("../reaktive")
}
if (file("../fx-utils").exists()) {
    includeBuild("../fx-utils")
}
if (file("../krobot").exists()) {
    includeBuild("../krobot")
}