apply plugin: 'kotlinx-serialization'
apply plugin: 'kotlin-kapt'
apply plugin: 'org.openjfx.javafxplugin'
apply plugin: 'maven-publish'
apply plugin: 'org.jetbrains.dokka'

version '1.1-SNAPSHOT'

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            artifact kotlinSourcesJar
        }
    }
}

kapt {
    useBuildCache = true
    annotationProcessors("hextant.codegen.MainProcessor")
}


javafx {
    version = property('javafx_version')
    modules = ['javafx.controls']
    configuration = 'api'
}

dependencies {
    api "de.schleifenkauz:reaktive:1.0-SNAPSHOT"
    api "de.schleifenkauz:bundles:1.0-SNAPSHOT"
    api "de.schleifenkauz:kollektion:1.0-SNAPSHOT"
    api "de.schleifenkauz:fx-utils:1.0-SNAPSHOT"

    implementation 'org.kordamp.ikonli:ikonli-materialdesign2-pack:12.3.1'
    implementation 'org.kordamp.ikonli:ikonli-codicons-pack:12.3.1'
    implementation 'org.kordamp.ikonli:ikonli-evaicons-pack:12.3.1'
    implementation 'org.kordamp.ikonli:ikonli-material2-pack:12.3.1'

    implementation 'com.github.kwhat:jnativehook:2.2.2'

    api project(':hextant-codegen')
    kapt project(":hextant-codegen")
    api project(':hextant-plugins:hextant-common')

    api 'org.jetbrains.kotlin:kotlin-stdlib-common'
    api 'org.jetbrains.kotlin:kotlin-reflect'
    api "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2'

    testImplementation project(":hextant-expr")
    testImplementation project(":hextant-test")
}